export const en = {
  header: {
    nav: {
      games: "Games",
      about: "About",
      contact: "Contact",
      privacy: "Privacy",
    },
  },
  about: {
    title: "About",
    description: `We are an independent game development studio passionate about crafting immersive digital
     experiences. Our team brings together artists, engineers, and storytellers who share a vision of creating games that push boundaries and captivate players worldwide.
    From concept art to final release, every detail is meticulously designed to deliver unforgettable gameplay. 
    We believe in the power of interactive entertainment to inspire, challenge, and connect people across the globe.`,
  },
  games: {
    title: "Games",
  },
  gamePage: {
    about: {
      title: "About",
    },
    download: {
      title: "Download",
    },
    playDemo: "Try demo",
    games: {
      geohell: {
        description: `GeoHell is a fast-paced 2D platformer where you control a cube trapped in a dark and unforgiving world. Navigate through deadly obstacles and relentless enemies that can eliminate you with a single touch. The further you progress, the more intense and challenging the journey becomes.
         Dodge every hazard, survive as long as you can, and beat your highest distance record.`,
      },
      deadblok: {
        description: `Dead Blok is a fast-paced action game. Master the controls and clear the levels.`,
      },
    },
  },
  footer: {
    privacyPolicy: "Privacy Policy",
    copyright: "All rights reserved.",
    privacyLink: {} as Record<string, string>,
  },
  contact: {
    title: "Contact",
  },
  privacyPage: {
    title: "Privacy Policy",
    lastUpdated: "Last updated: 16.02.2026",
    paragraphs: [
      `This Privacy Policy describes how we collect, use, and protect information when you use our games and visit our website. By using our services, you agree to the practices described below.`,
      `We may collect minimal data necessary to provide and improve our games (for example, in-game progress or device information). We do not sell your personal data to third parties.`,
      `Our games may use third-party services (such as analytics or ads) that have their own privacy policies. We encourage you to review those policies.`,
      `We may update this policy from time to time. Continued use of our services after changes constitutes acceptance of the updated policy.`,
      `If you have questions about this Privacy Policy, please contact us through the channels provided on our website.`,
    ],
    games: {
      geohell: {
        title: "GeoHell — Privacy Policy",
        lastUpdated: "Last updated: 16.02.2026",
        paragraphs: [
          `The app does not require account creation and can be played offline. Certain data is collected automatically to support gameplay features and improve app stability.`,
          `Information We Collect
The app may collect the following types of data:
• Gameplay data, such as completed levels, scores, and leaderboard entries
• User-provided name, such as a nickname generated by the player for leaderboards
• App usage data, including in-game events and interactions (via Firebase Analytics)
• Crash and diagnostic data, such as crash logs and device information (via Firebase Crashlytics)
• Device or installation identifiers, generated automatically to associate gameplay data with a device or app instance`,
          `Optional Online Features
The game includes optional online features such as global leaderboards. Participation in these features is optional and not required to play the game.

The game may also offer optional sign-in using Google Play Games Services. If you choose to sign in, Google may provide a player identifier and display name, which may be used for leaderboards and achievements.`,
          `How We Use the Data
• To store and restore game progress
• To display leaderboard rankings
• To analyze gameplay behavior and improve game balance
• To detect, diagnose, and fix crashes and technical issues`,
          `Data Sharing
We do not sell or share personal data for advertising or marketing purposes. Data is processed and stored securely using trusted third-party service providers, including Google Firebase and Google Play Games Services, solely for app functionality and analytics purposes.`,
          `Data Security
Data transmitted by the app is encrypted in transit using industry-standard security measures.`,
          `Children's Privacy
The game does not knowingly collect personal information such as real names, email addresses, phone numbers, or precise location data.`,
          `Changes to This Policy
This Privacy Policy may be updated from time to time. Any changes will be reflected on this page.`,
          `Contact
If you have any questions about this Privacy Policy, you can contact the developer at: leafplaybusiness@gmail.com`,
        ],
      },
      deadblok: {
        title: "Dead Blok — Privacy Policy",
        lastUpdated: "Last updated: 16.02.2026",
        paragraphs: [
          `This Privacy Policy applies to the game Dead Blok. By playing Dead Blok, you agree to the practices described below.`,
          `We may collect minimal data necessary to run and improve the game (for example, in-game progress or device information). We do not sell your personal data to third parties.`,
          `Dead Blok may use third-party services (such as analytics or advertising) that have their own privacy policies. We encourage you to review those policies.`,
          `We may update this policy from time to time. Continued use of Dead Blok after changes constitutes acceptance of the updated policy.`,
          `If you have questions about this Privacy Policy, please contact us through the channels provided on our website.`,
        ],
      },
    },
  },
} as const;

export type LocaleEn = typeof en;
